### ISSUE TITLE
Create site styleguide

### ISSUE THREAD

**Issue by mejiaj** [Bixal/bixal-site-drupal#1]
Collect Bixal site components to audit and apply consistent styles.

**Identified components**

- [x] Button
- [x] Typography
- [x] Multi column list (_ex: [Careers benefits list](https://www.bixal.com/careers/#:~:text=COMPETITIVE%20BASE%20SALARY,WITH%20EMPLOYER%20MATCH)_)
- [x] Description list
- [x] Hero
- [x] Callout section
- [x] Flippy cards
- [x] Header
- [x] Footer
- [x] Form elements (Contact us)
- [x] Contact us form
- [x] Emphasis block (_ex: [job block](https://www.bixal.com/careers/#:~:text=VIEW%20ALL%20JOBS-,Featured%20Jobs,-STRATEGIC%20GROWTH)_)
- [x] Image list (_ex: [people list](https://www.bixal.com/about/#:~:text=empathy%20and%20understanding.-,Meet%20Team%20Bixal,-An%20organization%20is)_)
- [x] Profile (_ex: https://www.bixal.com/about/brad-mash/_) 
- [x] Pillar (_ex: [Pillar](https://www.bixal.com/about/#:~:text=People%2Dabsolutely%2Dfirst.,across%20our%20entire%20team.)_)

### Todo

As a follow-up. Also need to breakdown Case Studies, both list and individual.

- https://www.bixal.com/our-work/
- https://www.bixal.com/our-work/digital-apex/
- [Icon list](https://www.bixal.com/our-work/hhs/#:~:text=Drupal%209%2C%20USAJOBS%20API%2C%20React.js%2C%20Leaflet%20Map%20API)
- Blog columns (Like pillar, but clickable. Ex: https://www.bixal.com/blog/)
- [Key points](https://www.bixal.com/contract-vehicles/eval-me-ii-idiq)
